### PR TITLE
Add parameter for source

### PR DESCRIPTION
**Pull request by kytomaki**
* Use parameter to set packages source
* Also use newer gpgtools

### CODE REVIEW

**Comment by tarebyte** [comment]
Hi @kytomaki instead of making the whole url the parameter, why not just the release version?

For example

```puppet
# Install GPGTools.
class gpgtools (
  $version = '2015.03-b6',
) {
  package { 'GPGTools':
    name     => 'GPGTools.pkg',
    provider => 'pkgdmg',
    source   => "https://releases.gpgtools.org/GPG_Suite-${version}.dmg",
  }
}
```

**Comment by kytomaki** [comment]
That's an excellent idea. I'll update the pull-request in a minute.

**Comment by kytomaki** [comment]
Hello @tarebyte I rebased the pull-request into a single commit.

**Comment by tarebyte** [comment]
:sparkles:

**Pull request merged**
